name: $(Build.DefinitionName)-$(BuildID)-$(date:yyyyMMdd)$(rev:.r)
trigger:
  branches:
    include:
    - master
  paths:
      include:
      - ./api/*
      - ./api-azure-pipelines.yml

variables:
  System.Debug: true
  buildConfiguration: 'Release'
  subscription: 'bushapp-subscription'
  envSuffix: 'dev1'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build_test_and_publish
  jobs:
  - job: test
    displayName: Run tests
    steps:

    - task: UseDotNet@2 
      displayName: ".NET Core 3.1.x"
      inputs:
        version: '3.1.x'
        packageType: sdk

    - script: dotnet build --configuration $(buildConfiguration)
      workingDirectory: 'api'
      displayName: 'dotnet build $(buildConfiguration)'

    - script: dotnet tool restore
      workingDirectory: 'api/bushApp.api'
      displayName: 'install local project dotnet tools'

    - script: dotnet swagger tofile --output '$(Build.ArtifactStagingDirectory)/swagger.json' --serializeasv2 --host 'https://bushapp-api-${{ variables.envSuffix }}.azurewebsites.net'  './bin/$(buildConfiguration)/netcoreapp3.1/bushApp.api.dll' v1
      workingDirectory: 'api/bushApp.api'
      displayName: 'generate swagger.json'

    - task: DotNetCoreCLI@2
      displayName: "Test"
      inputs:
        workingDirectory: 'api/bushApp.api.test'
        command: test
        projects: '*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: "Dotnet Publish"
      inputs:
        workingDirectory: 'api/bushApp.api'
        command: 'publish'
        publishWebProjects: true
        arguments: '-r linux-x64 --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - publish: '$(Build.ArtifactStagingDirectory)'
      displayName: "Upload built api"
      artifact: WebApp  
      
    - publish: '$(Build.SourcesDirectory)/arm'
      displayName: "Upload arm templates"
      artifact: ArmTemplates  

- stage: deploy_to_test
  dependsOn:
  - build_test_and_publish

  jobs:
  - template: templates/deploy-api.yml
    parameters:
      azureSubscription: '$(subscription)'
      resourceGroupPrefix: 'bushapp-rg'
      envSuffix: '${{ variables.envSuffix }}'

