name: $(Build.DefinitionName)-$(BuildID)-$(date:yyyyMMdd)$(rev:.r)
trigger:
  branches:
    include:
    - master
  paths:
      include:
      - ./api/*
      - ./api-azure-pipelines.yml

stages:
- stage: test
  jobs:
  - job: test
    displayName: Run tests
    steps:
    - task: DotNetCoreCLI@2
      displayName: Run unit tests
      inputs:
        command: test
        arguments: /p:CollectCoverage=true /p:Exclude="[xunit.*]*%2c[*]bushapp.api.Startup%2c[*]bushapp.api.Program" /p:CoverletOutputFormat=cobertura /p:Threshold=95 /p:ThresholdType=Line /p:verbosity=diag /p:nodereuse=false
        workingDirectory: 'bushapp.api.test'

