name: $(Build.DefinitionName)-$(BuildID)-$(date:yyyyMMdd)$(rev:.r)
trigger:
  branches:
    include:
    - master
  paths:
      include:
      - ./api/*
      - ./api-azure-pipelines.yml

variables:
  System.Debug: true
  buildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: test_and_publish
  jobs:
  - job: test
    displayName: Run tests
    steps:

    - task: UseDotNet@2 
      displayName: ".NET Core 3.1.x"
      inputs:
        version: '3.1.x'
        packageType: sdk

    - script: dotnet build --configuration $(buildConfiguration)
      workingDirectory: 'api'
      displayName: 'dotnet build $(buildConfiguration)'

    - script: dotnet tool restore
      workingDirectory: 'api/bushApp.api'
      displayName: 'install local project dotnet tools'

    - script: dotnet swagger tofile --output '$(Build.ArtifactStagingDirectory)/swagger.json' --host 'https://bushapp-api.azurewebsites.net'  './bin/$(buildConfiguration)/netcoreapp3.1/bushApp.api.dll' v1
      workingDirectory: 'api/bushApp.api'
      displayName: 'generate swagger.json'

    - task: DotNetCoreCLI@2
      displayName: "Test"
      inputs:
        workingDirectory: 'api/bushApp.api.test'
        command: test
        projects: '*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: "Publish"
      inputs:
        workingDirectory: 'api/bushApp.api'
        command: 'publish'
        publishWebProjects: true
        arguments: '-r linux-x64 --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: "Upload Artifacts"
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'bushApp.api' 

    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy to linux Azure Web App'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'bushapp-aus-east'
        appType: 'webAppLinux'
        WebAppName: 'bushapp-api'
        packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'
        RuntimeStack: 'DOTNETCORE|3.1'


    - task: AzureCLI@2
      inputs:
        azureSubscription: 'bushapp-aus-east'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $apim = az apim show `
            --resource-group-name 'bushapp-aus-east' `
            --name 'bushapp-apim'

          echo $apim
          
          $api = az apim api import `
            --resource-group $apim.ResourceGroupName `
            --service-name $apim.Name `
            --api-id 'bushapp-api' `
            --path 'bushapp' `
            --specification-format 'Swagger' `
            --specification-path '$(Build.ArtifactStagingDirectory)/swagger.json'