# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  System.Debug: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: Install dependencies and build
  workingDirectory: bushApp

- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/bushApp/dist'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/bushApp'
    CleanTargetFolder: true

- task: ArchiveFiles@2
  displayName: 'Zip Up bushApp frontend Files'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/bushApp'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/bushApp' 
    artifactName: 'bushApp'

- task: AzureCLI@2
  displayName: Copy bushApp to blob storage
  inputs:
    azureSubscription: <Name of the Azure Resource Manager service connection>
    scriptType: 'pscore'
    scriptLocation: inlineScript
    inlineScript: |
      az storage blob upload-batch — account-name STORAGE_ACCOUNT_NAME account-key STORAGE_ACCOUNT_KEY — destination ‘$web’ — source ./
