# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  System.Debug: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: Install dependencies and build
  workingDirectory: bushApp

- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/bushApp/dist'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/bushApp'
    CleanTargetFolder: true

- task: ArchiveFiles@2
  displayName: 'Zip Up bushApp frontend Files'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/bushApp'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/bushApp' 
    artifactName: 'bushApp'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      ls '$(Build.ArtifactStagingDirectory)/bushApp/bushApp'

- task: AzureCLI@2
  displayName: Copy bushApp to blob storage
  inputs:
    azureSubscription: Visual Studio Enterprise Subscription(ee4309f4-7551-411b-8001-6c0a0dd91750)
    scriptType: 'pscore'
    scriptLocation: inlineScript
    inlineScript: |
      az storage blob upload-batch — account-name bushstorageauseast account-key epvWcHdMI/vIhT+AB9dqR6c+/mFMpsQQBSMVc9mro9SHIQQ2Yl+etdgmZdJXNqNHpt32uo9m9jLTCeYGqTtvCg== — destination ‘$web’ — source $(Build.SourcesDirectory)/bushApp/dist
